# Generated by Django 5.1.1 on 2024-10-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
